[package]
name = "jbl_calc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tramp = "0.3.0"

[dependencies.clap]
version = "3.1.6"
features = ["derive"]